
<statement>     ::= <if-statement>
                | <function-statement>

<function-statement>    ::= function <identifier> ( <identifier-list> ) { <body-statement> }

<if-statement>  ::= if (<expression>) { <body-statement> }

<body-statement>    ::= <basic-statement> ;
                    | <basic-statement> ; <body-statement>
                    | <if-statement>
                    | <if-statement> <body-statement>


<basic-statement>   ::= <assign-statement>
                    | <call-expression>
                    | <return-statement>

<return-statement>  ::= return <expression>

<assign-statement>     ::= <identifier> = <expression> ;


<expression>    ::= <arithmetic-expression>
                  | <call-expression>

<call-expression>       ::= <identifier> ( <identifier-list> ) ;

<arithmetic-expression> ::= <term>
                        | <term> + <arithmetic-expression>
                        | <term> - <arithmetic-expression>

<term>      ::= <factor>
            | <factor> * <term>
            | <factor> / <term>

// "hello", 123, userName
<factor>    ::= <primary> | <identifier>

// "hello", 123
<primary>   ::= <string> | <number>

// userName, Age
<identifier-list>       ::= <identifier>
                        | <identifier> , <identifier-list>

// useName
<identifier>    ::= [a-z][A-Z]

<string>    ::= '<charactoers>'
            | ''
<characters>    ::= <character>
                | <character> <characters>


<number>    ::= <integer>
<integer>   ::= <decimal digit>
            | <decimal digit> <integer>
<decimal digit>     ::= 0|1|2|3|4|5|6|7|8|9
